ext:
  outputs:
    dev:
      catalog: null
      host: adb-XXXXXXXXXXXXX.13.azuredatabricks.net
      http_path: sql/protocolv1/o/XXXXXXXXXXXXXXXX/XXXX-XXXXXX-XXXXXXXXXX
      schema: ext_test
      threads: 1
      token: dapiXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      type: databricks
  target: dev
